<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;
use PhpOffice\PhpSpreadsheet\Shared\Date;
class EmployeeDashboardSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

     
            DB::table('employee_application_details')->insertOrIgnore(array(
                array(
                    'employee_name'=>'Akshat Sawant',
                    'employee_id'=>'1',
                    'application_number'=>'1',
                    'customer_name'=>'Akshat Sawant',
                    'product_type'=>'LAP',
                    'application_status'=>'Logged In',
                    'applied_amount'=>(double)10,
                    'sanctioned_amount'=>(double)10,
                    'disbursed_amount'=>(double)4,
                    'application_login_date'=>'2020-07-16 00:00:00',
                    'sanctioned_date'=>'2020-07-16 00:00:00',
                    'declined_date'=>'2020-07-16 00:00:00',
                    'disbursement_date'=>'2020-07-16 00:00:00',
                    'sales_officer_name'=>'namrata',
                    'sales_supervisors_name'=>'namrata',
                    'sourcing_location'=>'thane',
                    'sourcing_agency'=>'asd',
                    'updated_at'=>now(),
               ),
                array(
                    'employee_name'=>'Akshat Sawant',
                    'employee_id'=>'1',
                    'application_number'=>'2',
                    'customer_name'=>'Akshat Sawant',
                    'product_type'=>'LAP',
                    'application_status'=>'Sanctioned',
                    'applied_amount'=>(double)20,
                    'sanctioned_amount'=>(double)20,
                    'disbursed_amount'=>(double)10,
                    'application_login_date'=>'2020-07-16 00:00:00',
                    'sanctioned_date'=>'2020-07-16 00:00:00',
                    'declined_date'=>'2020-07-16 00:00:00',
                    'disbursement_date'=>'2020-07-16 00:00:00',
                    'sales_officer_name'=>'namrata',
                    'sales_supervisors_name'=>'namrata',
                    'sourcing_location'=>'thane',
                    'sourcing_agency'=>'asd',
                    'updated_at'=>now(),
                 ),
                array(
                'employee_name'=>'Akshat Sawant',
                'employee_id'=>'1',
                'application_number'=>'3',
                'customer_name'=>'Akshat Sawant',
                'product_type'=>'LAP',
                'application_status'=>'Declined',
                'applied_amount'=>(double)30,
                'sanctioned_amount'=>(double)20,
                'disbursed_amount'=>(double)10,
                'application_login_date'=>'2020-07-16 00:00:00',
                'sanctioned_date'=>'2020-07-16 00:00:00',
                'declined_date'=>'2020-07-16 00:00:00',
                'disbursement_date'=>'2020-07-16 00:00:00',
                'sales_officer_name'=>'namrata',
                'sales_supervisors_name'=>'namrata',
                'sourcing_location'=>'thane',
                'sourcing_agency'=>'asd',
                'updated_at'=>now(),
                ),
                array(
                    'employee_name'=>'Akshat Sawant',
                    'employee_id'=>'1',
                    'application_number'=>'4',
                    'customer_name'=>'Akshat Sawant',
                    'product_type'=>'LAP',
                    'application_status'=>'Declined',
                    'applied_amount'=>(double)40,
                    'sanctioned_amount'=>(double)20,
                    'disbursed_amount'=>(double)10,
                    'application_login_date'=>'2020-07-16 00:00:00',
                    'sanctioned_date'=>'2020-07-16 00:00:00',
                    'declined_date'=>'2020-07-16 00:00:00',
                    'disbursement_date'=>'2020-07-16 00:00:00',
                    'sales_officer_name'=>'namrata',
                    'sales_supervisors_name'=>'namrata',
                    'sourcing_location'=>'thane',
                    'sourcing_agency'=>'asd',
                    'updated_at'=>now(),
                ),
                array(
                    'employee_name'=>'Akshat Sawant',
                    'employee_id'=>'1',
                    'application_number'=>'5',
                    'customer_name'=>'Akshat Sawant',
                    'product_type'=>'LAP',
                    'application_status'=>'Disbursed',
                    'applied_amount'=>(double)50,
                    'sanctioned_amount'=>(double)20,
                    'disbursed_amount'=>(double)10,
                    'application_login_date'=>'2020-07-16 00:00:00',
                    'sanctioned_date'=>'2020-07-16 00:00:00',
                    'declined_date'=>'2020-07-16 00:00:00',
                    'disbursement_date'=>'2020-07-16 00:00:00',
                    'sales_officer_name'=>'namrata',
                    'sales_supervisors_name'=>'namrata',
                    'sourcing_location'=>'thane',
                    'sourcing_agency'=>'asd',
                    'updated_at'=>now(),
                ),
                array(
                    'employee_name'=>'Akshat Sawant',
                    'employee_id'=>'1',
                    'application_number'=>'6',
                    'customer_name'=>'Akshat Sawant',
                    'product_type'=>'LAP',
                    'application_status'=>'Partially Disbursed',
                    'applied_amount'=>(double)60,
                    'sanctioned_amount'=>(double)20,
                    'disbursed_amount'=>(double)10,
                    'application_login_date'=>'2020-07-16 00:00:00',
                    'sanctioned_date'=>'2020-07-16 00:00:00',
                    'declined_date'=>'2020-07-16 00:00:00',
                    'disbursement_date'=>'2020-07-16 00:00:00',
                    'sales_officer_name'=>'namrata',
                    'sales_supervisors_name'=>'namrata',
                    'sourcing_location'=>'thane',
                    'sourcing_agency'=>'asd',
                    'updated_at'=>now(),
                ),array(
                    'employee_name'=>'Akshat Sawant',
                    'employee_id'=>'1',
                    'application_number'=>'7',
                    'customer_name'=>'Akshat Sawant',
                    'product_type'=>'LAP',
                    'application_status'=>'Logged In',
                    'applied_amount'=>(double)10,
                    'sanctioned_amount'=>(double)10,
                    'disbursed_amount'=>(double)4,
                    'application_login_date'=>'2020-06-16 00:00:00',
                    'sanctioned_date'=>'2020-06-16 00:00:00',
                    'declined_date'=>'2020-06-16 00:00:00',
                    'disbursement_date'=>'2020-06-16 00:00:00',
                    'sales_officer_name'=>'namrata',
                    'sales_supervisors_name'=>'namrata',
                    'sourcing_location'=>'thane',
                    'sourcing_agency'=>'asd',
                    'updated_at'=>now(),
                ),
                array(
                    'employee_name'=>'Akshat Sawant',
                    'employee_id'=>'1',
                    'application_number'=>'8',
                    'customer_name'=>'Akshat Sawant',
                    'product_type'=>'LAP',
                    'application_status'=>'Sanctioned',
                    'applied_amount'=>(double)20,
                    'sanctioned_amount'=>(double)20,
                    'disbursed_amount'=>(double)10,
                    'application_login_date'=>'2020-06-16 00:00:00',
                    'sanctioned_date'=>'2020-06-16 00:00:00',
                    'declined_date'=>'2020-06-16 00:00:00',
                    'disbursement_date'=>'2020-06-16 00:00:00',
                    'sales_officer_name'=>'namrata',
                    'sales_supervisors_name'=>'namrata',
                    'sourcing_location'=>'thane',
                    'sourcing_agency'=>'asd',
                    'updated_at'=>now(),
                ),
                array(
                    'employee_name'=>'Akshat Sawant',
                    'employee_id'=>'1',
                    'application_number'=>'9',
                    'customer_name'=>'Akshat Sawant',
                    'product_type'=>'LAP',
                    'application_status'=>'Declined',
                    'applied_amount'=>(double)30,
                    'sanctioned_amount'=>(double)20,
                    'disbursed_amount'=>(double)10,
                    'application_login_date'=>'2020-06-16 00:00:00',
                    'sanctioned_date'=>'2020-06-16 00:00:00',
                    'declined_date'=>'2020-06-16 00:00:00',
                    'disbursement_date'=>'2020-06-16 00:00:00',
                    'sales_officer_name'=>'namrata',
                    'sales_supervisors_name'=>'namrata',
                    'sourcing_location'=>'thane',
                    'sourcing_agency'=>'asd',
                    'updated_at'=>now(),
                ),
                array(
                    'employee_name'=>'Akshat Sawant',
                    'employee_id'=>'1',
                    'application_number'=>'10',
                    'customer_name'=>'Akshat Sawant',
                    'product_type'=>'LAP',
                    'application_status'=>'Declined',
                    'applied_amount'=>(double)40,
                    'sanctioned_amount'=>(double)20,
                    'disbursed_amount'=>(double)10,
                    'application_login_date'=>'2020-06-16 00:00:00',
                    'sanctioned_date'=>'2020-06-16 00:00:00',
                    'declined_date'=>'2020-06-16 00:00:00',
                    'disbursement_date'=>'2020-06-16 00:00:00',
                    'sales_officer_name'=>'namrata',
                    'sales_supervisors_name'=>'namrata',
                    'sourcing_location'=>'thane',
                    'sourcing_agency'=>'asd',
                    'updated_at'=>now(),
                ),
                array(
                    'employee_name'=>'Akshat Sawant',
                    'employee_id'=>'1',
                    'application_number'=>'11',
                    'customer_name'=>'Akshat Sawant',
                    'product_type'=>'LAP',
                    'application_status'=>'Disbursed',
                    'applied_amount'=>(double)50,
                    'sanctioned_amount'=>(double)20,
                    'disbursed_amount'=>(double)10,
                    'application_login_date'=>'2020-06-16 00:00:00',
                    'sanctioned_date'=>'2020-06-16 00:00:00',
                    'declined_date'=>'2020-06-16 00:00:00',
                    'disbursement_date'=>'2020-06-16 00:00:00',
                    'sales_officer_name'=>'namrata',
                    'sales_supervisors_name'=>'namrata',
                    'sourcing_location'=>'thane',
                    'sourcing_agency'=>'asd',
                    'updated_at'=>now(),
                ),
                array(
                    'employee_name'=>'Akshat Sawant',
                    'employee_id'=>'1',
                    'application_number'=>'12',
                    'customer_name'=>'Akshat Sawant',
                    'product_type'=>'LAP',
                    'application_status'=>'Partially Disbursed',
                    'applied_amount'=>(double)60,
                    'sanctioned_amount'=>(double)20,
                    'disbursed_amount'=>(double)10,
                    'application_login_date'=>'2020-06-16 00:00:00',
                    'sanctioned_date'=>'2020-06-16 00:00:00',
                    'declined_date'=>'2020-06-16 00:00:00',
                    'disbursement_date'=>'2020-06-16 00:00:00',
                    'sales_officer_name'=>'namrata',
                    'sales_supervisors_name'=>'namrata',
                    'sourcing_location'=>'thane',
                    'sourcing_agency'=>'asd',
                    'updated_at'=>now(),
                ),
                array(
                    'employee_name'=>'Akshat Sawant',
                    'employee_id'=>'1',
                    'application_number'=>'13',
                    'customer_name'=>'Akshat Sawant',
                    'product_type'=>'LAP',
                    'application_status'=>'Partially Disbursed',
                    'applied_amount'=>(double)60,
                    'sanctioned_amount'=>(double)20,
                    'disbursed_amount'=>(double)10,
                    'application_login_date'=>'2020-06-16 00:00:00',
                    'sanctioned_date'=>'2020-06-16 00:00:00',
                    'declined_date'=>'2020-06-16 00:00:00',
                    'disbursement_date'=>'2020-06-16 00:00:00',
                    'sales_officer_name'=>'namrata',
                    'sales_supervisors_name'=>'namrata',
                    'sourcing_location'=>'thane',
                    'sourcing_agency'=>'asd',
                    'updated_at'=>now(),
                ),
                array(
                    'employee_name'=>'Akshat Sawant',
                    'employee_id'=>'1',
                    'application_number'=>'14',
                    'customer_name'=>'Akshat Sawant',
                    'product_type'=>'LAP',
                    'application_status'=>'Logged In',
                    'applied_amount'=>(double)10,
                    'sanctioned_amount'=>(double)10,
                    'disbursed_amount'=>(double)10,
                    'application_login_date'=>'2020-05-16 00:00:00',
                    'sanctioned_date'=>'2020-05-16 00:00:00',
                    'declined_date'=>'2020-05-16 00:00:00',
                    'disbursement_date'=>'2020-05-16 00:00:00',
                    'sales_officer_name'=>'namrata',
                    'sales_supervisors_name'=>'namrata',
                    'sourcing_location'=>'thane',
                    'sourcing_agency'=>'asd',
                    'updated_at'=>now(),
                ),
                array(
                    'employee_name'=>'Akshat Sawant',
                    'employee_id'=>'1',
                    'application_number'=>'15',
                    'customer_name'=>'Akshat Sawant',
                    'product_type'=>'LAP',
                    'application_status'=>'Sanctioned',
                    'applied_amount'=>(double)20,
                    'sanctioned_amount'=>(double)20,
                    'disbursed_amount'=>(double)10,
                    'application_login_date'=>'2020-05-16 00:00:00',
                    'sanctioned_date'=>'2020-05-16 00:00:00',
                    'declined_date'=>'2020-05-16 00:00:00',
                    'disbursement_date'=>'2020-05-16 00:00:00',
                    'sales_officer_name'=>'namrata',
                    'sales_supervisors_name'=>'namrata',
                    'sourcing_location'=>'thane',
                    'sourcing_agency'=>'asd',
                    'updated_at'=>now(),
                ),
                array(
                    'employee_name'=>'Akshat Sawant',
                    'employee_id'=>'1',
                    'application_number'=>'16',
                    'customer_name'=>'Akshat Sawant',
                    'product_type'=>'LAP',
                    'application_status'=>'Declined',
                    'applied_amount'=>(double)30,
                    'sanctioned_amount'=>(double)20,
                    'disbursed_amount'=>(double)10,
                    'application_login_date'=>'2020-05-16 00:00:00',
                    'sanctioned_date'=>'2020-05-16 00:00:00',
                    'declined_date'=>'2020-05-16 00:00:00',
                    'disbursement_date'=>'2020-05-16 00:00:00',
                    'sales_officer_name'=>'namrata',
                    'sales_supervisors_name'=>'namrata',
                    'sourcing_location'=>'thane',
                    'sourcing_agency'=>'asd',
                    'updated_at'=>now(),
                ),
                array(
                    'employee_name'=>'Akshat Sawant',
                    'employee_id'=>'1',
                    'application_number'=>'17',
                    'customer_name'=>'Akshat Sawant',
                    'product_type'=>'LAP',
                    'application_status'=>'Declined',
                    'applied_amount'=>(double)40,
                    'sanctioned_amount'=>(double)20,
                    'disbursed_amount'=>(double)10,
                    'application_login_date'=>'2020-05-16 00:00:00',
                    'sanctioned_date'=>'2020-05-16 00:00:00',
                    'declined_date'=>'2020-05-16 00:00:00',
                    'disbursement_date'=>'2020-05-16 00:00:00',
                    'sales_officer_name'=>'namrata',
                    'sales_supervisors_name'=>'namrata',
                    'sourcing_location'=>'thane',
                    'sourcing_agency'=>'asd',
                    'updated_at'=>now(),
                ),
                array(
                    'employee_name'=>'Akshat Sawant',
                    'employee_id'=>'1',
                    'application_number'=>'18',
                    'customer_name'=>'Akshat Sawant',
                    'product_type'=>'LAP',
                    'application_status'=>'Disbursed',
                    'applied_amount'=>(double)50,
                    'sanctioned_amount'=>(double)20,
                    'disbursed_amount'=>(double)10,
                    'application_login_date'=>'2020-05-16 00:00:00',
                    'sanctioned_date'=>'2020-05-16 00:00:00',
                    'declined_date'=>'2020-05-16 00:00:00',
                    'disbursement_date'=>'2020-05-16 00:00:00',
                    'sales_officer_name'=>'namrata',
                    'sales_supervisors_name'=>'namrata',
                    'sourcing_location'=>'thane',
                    'sourcing_agency'=>'asd',
                    'updated_at'=>now(),
                ),
                array(
                    'employee_name'=>'Akshat Sawant',
                    'employee_id'=>'1',
                    'application_number'=>'19',
                    'customer_name'=>'Akshat Sawant',
                    'product_type'=>'LAP',
                    'application_status'=>'Partially Disbursed',
                    'applied_amount'=>(double)60,
                    'sanctioned_amount'=>(double)20,
                    'disbursed_amount'=>(double)10,
                    'application_login_date'=>'2020-05-16 00:00:00',
                    'sanctioned_date'=>'2020-05-16 00:00:00',
                    'declined_date'=>'2020-05-16 00:00:00',
                    'disbursement_date'=>'2020-05-16 00:00:00',
                    'sales_officer_name'=>'namrata',
                    'sales_supervisors_name'=>'namrata',
                    'sourcing_location'=>'thane',
                    'sourcing_agency'=>'asd',
                    'updated_at'=>now(),
                ),
                array(
                    'employee_name'=>'Akshat Sawant',
                    'employee_id'=>'1',
                    'application_number'=>'20',
                    'customer_name'=>'Akshat Sawant',
                    'product_type'=>'LAP',
                    'application_status'=>'Partially Disbursed',
                    'applied_amount'=>(double)60,
                    'sanctioned_amount'=>(double)20,
                    'disbursed_amount'=>(double)10,
                    'application_login_date'=>'2020-05-16 00:00:00',
                    'sanctioned_date'=>'2020-05-16 00:00:00',
                    'declined_date'=>'2020-05-16 00:00:00',
                    'disbursement_date'=>'2020-05-16 00:00:00',
                    'sales_officer_name'=>'namrata',
                    'sales_supervisors_name'=>'namrata',
                    'sourcing_location'=>'thane',
                    'sourcing_agency'=>'asd',
                    'updated_at'=>now(),
                ),

            ));

            DB::table('application_disburse_details')->insertOrIgnore(array(
                array(
                
                'employee_id'=>1,
                'application_number'=>6,
                'application_tbl_id'=>6,
                'application_status'=>'Partially  Disbursed',
                'disbursement_date'=>'2020-07-16 00:00:00',
                
                ),
                array(
                    'employee_id'=>1,
                    'application_number'=>12,
                    'application_tbl_id'=>12,
                    'application_status'=>'Partially  Disbursed',
                    'disbursement_date'=>'2020-06-16 00:00:00',
             ),
             array(
                'employee_id'=>1,
                'application_number'=>13,
                'application_tbl_id'=>13,
                'application_status'=>'Partially  Disbursed',
                'disbursement_date'=>'2020-06-16 00:00:00',
             ),
             array(
                'employee_id'=>1,
                'application_number'=>19,
                'application_tbl_id'=>19,
                'application_status'=>'Partially  Disbursed',
                'disbursement_date'=>'2020-05-16 00:00:00',
             ),
             array(
                'employee_id'=>1,
                'application_number'=>20,
                'application_tbl_id'=>20,
                'application_status'=>'Partially  Disbursed',
                'disbursement_date'=>'2020-05-16 00:00:00',
             ),
                
                
               
            ));

        }



       
}

